### ISSUE TITLE
trace_gen.py dramsim2 gen traces looks different

### ISSUE THREAD

**Issue by HaFred** [umd-memsys/DRAMsim3#12]
Hi, I would like to know how is the `dramsim2` flag used in dramsim2? Seems like the generated traces here https://github.com/umd-memsys/DRAMsim3/blob/master/scripts/trace_gen.py is different from the traces used in dramsim2.

**Comment by luyikang** [comment]
Try add parameter "-f dramsim2"?

**Comment by HaFred** [comment]
> Try add parameter "-f dramsim2"?

Actually I meant the traces generated with `-f dramsim2` do not match the dramsim2 format, or cannot be parsed by dramsim2.
