### ISSUE TITLE
HBM controller bug

### ISSUE THREAD

**Issue by albertsegura** [umd-memsys/DRAMsim3#4]
There is a bug in the memory controller for HBM. A command is removed from the command queue but never issued by the controller. That command is effectively never processed, and no reply is issued ever, potentially deadlocking the system.

The problem is in the issue of the second command at line [84 in the Controller:]( https://github.com/umd-memsys/DRAMsim3/blob/47dad81c66de45c235eacc9fd9391bbca7a84196/src/controller.cc#L84)
 https://github.com/umd-memsys/DRAMsim3/blob/47dad81c66de45c235eacc9fd9391bbca7a84196/src/controller.cc#L84-L92

Only for HBM two commands can be issued, so a second command is pulled from the command queues by CommandQueue::GetCommandToIssue(), **note that this operation removes the command from the queue**. For the controller to issue the command it has to evaluate the next two ifs to true. It might happen that both the first command and the second are reads or writes and so, that command is not issued. And since the CommandQueue::GetCommandToIssue() removes the command from the queue it is never processed.

**Comment by luyikang** [comment]
Thanks for the feedback. The second command will not be issued if both of them are read/write. A temporary fix would be adding the second command back to cmd_queue. We will post a fix in the latest commit.
