### ISSUE TITLE
[bug] dead lock in Controller::ScheduleTransaction

### ISSUE THREAD

**Issue by gxflying** [umd-memsys/DRAMSim3#43]
hi sir , I am studying DramSim3, and I find that there may result in dead lock in **_Controller::ScheduleTransaction_** when there is write after read dependency and when configuring _unified_queue_ to false in .ini file
the specific sernario is that:
1.  add a read request (with address **A** )into the read_queue_  by AddTransaction
2.  add some write request
3.  add a write request (with address **A**), and then the write_buffer_ is full, which is write_buffer_.size() == write_buffer_.capacity()
4. and the read request of step 1 is NOT finish yet by any reason
5. then the flow in the Controller::ScheduleTransaction() will be dead lock and the read request of step 1 will never finished
    ****a**. whenever Controller::ScheduleTransaction is called**
    ****b**.  write_draining_ will be set to write_buffer_.size()**
https://github.com/umd-memsys/DRAMsim3/blob/29817593b3389f1337235d63cac515024ab8fd6e/src/controller.cc#L203
    ****c**.  scheduled queue will be write_buffer_**
https://github.com/umd-memsys/DRAMsim3/blob/29817593b3389f1337235d63cac515024ab8fd6e/src/controller.cc#L207
    ****d**.  iterate the element of the write_buffer_** 
    ****e**. find the write after read dependency, and set  write_draining_ to 0,  and finish the iteration without  any transaction scheduled**
https://github.com/umd-memsys/DRAMsim3/blob/29817593b3389f1337235d63cac515024ab8fd6e/src/controller.cc#L216
https://github.com/umd-memsys/DRAMsim3/blob/29817593b3389f1337235d63cac515024ab8fd6e/src/controller.cc#L217
    ****f**.  go to step **a****
 

acctually this is from one of my test case

hope your reply~

**Comment by imanthoc** [comment]
Hello Mr Felix, I have encountered the same problem, if you have found a solution I would be glad if you shared it.

**Comment by gxflying** [comment]
> Hello Mr Felix, I have encountered the same problem, if you have found a solution I would be glad if you shared it.

maybe you can have a try by adding the flowing pseudo code before the L218 ,  actrually I have NOT try this yet:
1.  check the read_queue_ to find whether there is a ready to issue cmd
2. if there is a ready to issue read cmd in read_queue_ , then add it into cmd_queue_ and erase it from read_queue_
3. if not  then do nothing 
the insight behind this  is whenever the dead lock is happened , maybe we should consume a read cmd
https://github.com/umd-memsys/DRAMsim3/blob/29817593b3389f1337235d63cac515024ab8fd6e/src/controller.cc#L218C1-L218C27

**Comment by joydddd** [comment]
Hi Felix,
Thanks for describing the bug and providing a fix! I've implemented the fix and so far it looks good.

**Comment by gxflying** [comment]
my pleasure ~
