### ISSUE TITLE
Multiple trace file

### ISSUE THREAD

**Issue by avacoder42** [umd-memsys/DRAMsim3#6]
Hi,
While using the HMC2 config, I have 32 separate trace files(.cmdtrace) for each thread from Ramulator which I want to feed in DRAMsim3 to calculate power and energy.
How do I input multiple trace files? If I feed it separately, only channel 0 has valid results and others are invalid.
Kindly guide me on this, thanks

**Comment by kaustubhcs** [comment]
Curious to know how you solved it @luyikang ?

**Comment by avacoder42** [comment]
Hi @kaustubhcs!

I do recollect solving this, but need to relook into my code base. Will keep you posted if I get around it!

**Comment by kaustubhcs** [comment]
Thank you @avacoder42 

I am designing a GNN accelerator simulator with DRAMSim3 backend. 
And your solution would be helpful in determining the validity of my results :)

**Comment by avacoder42** [comment]
Hi @kaustubhcs!

Looks like in the end, I moved to DRAMPower instead after trying to get DRAMSim3 working  . .
https://www.es.ele.tue.nl/drampower/
