### ISSUE TITLE
a question with command ./build/dramsim3main configs/DDR4_8Gb_x8_3200.ini -c 100000 -t sample_trace.txt

### ISSUE THREAD

**Issue by langrange-L** [umd-memsys/DRAMsim3#9]
when i run this command
./build/dramsim3main configs/DDR4_8Gb_x8_3200.ini -c 100000 -t sample_trace.txt
the result is:Trace file does not exist
Exiting Abruptly - /home/*/DRAMsim3-master/src/cpu.cc:69 
where is this Trace file ?

**Comment by luyikang** [comment]
Example trace is located in /test dir.
